name: TicTacToe
version: '${project.version}'
main: de.felixtpg.tictactoe.Main
api-version: 1.19
authors: [ FelixTPG ]

commands:
  setgamefieldlocation:
    description: Sets the position of the game field.